### ISSUE TITLE
Bug: failure to compile in Xcode 16.2 with Float16 type, missing `@available` for >= ios 14.0

### ISSUE THREAD

**Issue by brittlewis12** [unum-cloud/usearch#589]
### Describe the bug

Tried updating my project’s package dependency on usearch from 2.17.1 to 2.17.6 — got compilation errors suggesting to mark all the `Float16` methods as `@available` for only iOS 14 or later. I suppose an alternative could be declaring minimum supported OS versions in the Package.swift.

### Steps to reproduce

In my project targeting only iOS 17 or later, adding usearch 2.17.6 to package dependencies is enough to surface this compilation error.

### Expected behavior

No problems compiling for a project which only targets OS versions supported by all types and interfaces used.

### USearch version

2.17.6

### Operating System

macOS 15.3.2, targeting >= ios 17.0

### Hardware architecture

Arm

### Which interface are you using?

Other bindings

### Contact Details

brittlewis12@gmail.com

### Are you open to being tagged as a contributor?

- [x] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oboje** [comment]
up. Building for ios 17, same problem.

**Comment by hbcondo** [comment]
Same problem as well when trying to use USearch with UForm which `has a minimum deployment target of iOS 16.0`
